In [1]:
!ls ../data/raw

wine-quality.zip
winequalityN.csv

In [2]:
# imports
import pandas as pd
import numpy as np
import os

In [25]:
raw_data_path = os.path.join(os.path.pardir, 'data', 'raw')
train_filepath = os.path.join(raw_data_path, 'winequality-data.csv')
test_filepath = os.path.join(raw_data_path, 'winequality-solution-input.csv')

In [26]:
train_df = pd.read_csv(train_filepath, index_col='id')
test_df = pd.read_csv(test_filepath, index_col='id')

In [30]:
train_df.info()
print('\n\n')
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3918 entries, 981 to 4898
Data columns (total 12 columns):
fixed.acidity           3918 non-null float64
volatile.acidity        3918 non-null float64
citric.acid             3918 non-null float64
residual.sugar          3918 non-null float64
chlorides               3918 non-null float64
free.sulfur.dioxide     3918 non-null float64
total.sulfur.dioxide    3918 non-null float64
density                 3918 non-null float64
pH                      3918 non-null float64
sulphates               3918 non-null float64
alcohol                 3918 non-null float64
quality                 3918 non-null int64
dtypes: float64(11), int64(1)
memory usage: 397.9 KB



<class 'pandas.core.frame.DataFrame'>
Int64Index: 980 entries, 1 to 980
Data columns (total 11 columns):
fixed.acidity           980 non-null float64
volatile.acidity        980 non-null float64
citric.acid             980 non-null float64
residual.sugar          980 non-null float64
chlorides               980 non-null float64
free.sulfur.dioxide     980 non-null float64
total.sulfur.dioxide    980 non-null float64
density                 980 non-null float64
pH                      980 non-null float64
sulphates               980 non-null float64
alcohol                 980 non-null float64
dtypes: float64(11)
memory usage: 91.9 KB

In [31]:
train_df.head()

,fixed.acidity,volatile.acidity,citric.acid,residual.sugar,chlorides,free.sulfur.dioxide,total.sulfur.dioxide,density,pH,sulphates,alcohol,quality
id,,,,,,,,,,,,
981,6.7,0.15,0.38,1.7,0.037,20.0,84.0,0.99046,3.09,0.53,11.4,6
982,6.7,0.44,0.31,1.9,0.030,41.0,104.0,0.99000,3.29,0.62,12.6,7
983,6.1,0.17,0.21,1.9,0.090,44.0,130.0,0.99255,3.07,0.41,9.7,5
984,6.6,0.39,0.22,4.0,0.038,17.0,98.0,0.99018,3.25,0.53,13.0,7
985,6.8,0.32,0.34,6.0,0.050,5.0,129.0,0.99530,3.19,0.40,9.1,5

In [32]:
test_df.head()

,fixed.acidity,volatile.acidity,citric.acid,residual.sugar,chlorides,free.sulfur.dioxide,total.sulfur.dioxide,density,pH,sulphates,alcohol
id,,,,,,,,,,,
1,6.7,0.29,0.45,14.3,0.054,30.0,181.0,0.99869,3.14,0.57,9.1
2,7.4,0.32,0.55,16.6,0.056,53.0,238.0,1.00170,2.96,0.58,8.7
3,7.6,0.38,0.20,3.4,0.046,9.0,116.0,0.99440,3.15,0.41,9.4
4,7.9,0.14,0.45,1.8,0.050,17.0,114.0,0.99480,3.33,0.49,10.7
5,7.9,0.16,0.30,7.4,0.050,58.0,152.0,0.99612,3.12,0.37,9.5